/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AutoMove from "./Scripts/AutoMove"
import StartPanel from "./Scripts/StartPanel"
import Player from "./Scripts/Player"
import GameManager from "./Scripts/GameManager"
import Car from "./Scripts/Car"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("Scripts/AutoMove.js",AutoMove);
		reg("Scripts/StartPanel.js",StartPanel);
		reg("Scripts/Player.js",Player);
		reg("Scripts/GameManager.js",GameManager);
		reg("Scripts/Car.js",Car);
    }
}
GameConfig.width = 1080;
GameConfig.height = 1920;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
